version: "3"
services:
  web:
    build: ./
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - "./:/app"
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && rails server -p 3000 -b '0.0.0.0'"
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_USER=user123"
      - "DATABASE_PASSWORD=password123"
  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=user123"
      - "POSTGRES_PASSWORD=password123"