 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/news_signups", type: :request do
  # NewsSignup. As you add validations to NewsSignup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      NewsSignup.create! valid_attributes
      get news_signups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      news_signup = NewsSignup.create! valid_attributes
      get news_signup_url(news_signup)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_news_signup_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      news_signup = NewsSignup.create! valid_attributes
      get edit_news_signup_url(news_signup)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new NewsSignup" do
        expect {
          post news_signups_url, params: { news_signup: valid_attributes }
        }.to change(NewsSignup, :count).by(1)
      end

      it "redirects to the created news_signup" do
        post news_signups_url, params: { news_signup: valid_attributes }
        expect(response).to redirect_to(news_signup_url(NewsSignup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new NewsSignup" do
        expect {
          post news_signups_url, params: { news_signup: invalid_attributes }
        }.to change(NewsSignup, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post news_signups_url, params: { news_signup: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested news_signup" do
        news_signup = NewsSignup.create! valid_attributes
        patch news_signup_url(news_signup), params: { news_signup: new_attributes }
        news_signup.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the news_signup" do
        news_signup = NewsSignup.create! valid_attributes
        patch news_signup_url(news_signup), params: { news_signup: new_attributes }
        news_signup.reload
        expect(response).to redirect_to(news_signup_url(news_signup))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        news_signup = NewsSignup.create! valid_attributes
        patch news_signup_url(news_signup), params: { news_signup: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested news_signup" do
      news_signup = NewsSignup.create! valid_attributes
      expect {
        delete news_signup_url(news_signup)
      }.to change(NewsSignup, :count).by(-1)
    end

    it "redirects to the news_signups list" do
      news_signup = NewsSignup.create! valid_attributes
      delete news_signup_url(news_signup)
      expect(response).to redirect_to(news_signups_url)
    end
  end
end
