 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/supply_inventories", type: :request do
  # SupplyInventory. As you add validations to SupplyInventory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SupplyInventory.create! valid_attributes
      get supply_inventories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      supply_inventory = SupplyInventory.create! valid_attributes
      get supply_inventory_url(supply_inventory)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      supply_inventory = SupplyInventory.create! valid_attributes
      get new_supply_inventory_url(clinic_id: supply_inventory.clinic.id)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      supply_inventory = SupplyInventory.create! valid_attributes
      get edit_supply_inventory_url(supply_inventory)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SupplyInventory" do
        expect {
          post supply_inventories_url, params: { supply_inventory: valid_attributes }
        }.to change(SupplyInventory, :count).by(1)
      end

      it "redirects to the created supply_inventory" do
        post supply_inventories_url, params: { supply_inventory: valid_attributes }
        expect(response).to redirect_to(supply_inventory_url(SupplyInventory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SupplyInventory" do
        expect {
          post supply_inventories_url, params: { supply_inventory: invalid_attributes }
        }.to change(SupplyInventory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post supply_inventories_url, params: { supply_inventory: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested supply_inventory" do
        supply_inventory = SupplyInventory.create! valid_attributes
        patch supply_inventory_url(supply_inventory), params: { supply_inventory: new_attributes }
        supply_inventory.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the supply_inventory" do
        supply_inventory = SupplyInventory.create! valid_attributes
        patch supply_inventory_url(supply_inventory), params: { supply_inventory: new_attributes }
        supply_inventory.reload
        expect(response).to redirect_to(supply_inventory_url(supply_inventory))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        supply_inventory = SupplyInventory.create! valid_attributes
        patch supply_inventory_url(supply_inventory), params: { supply_inventory: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested supply_inventory" do
      supply_inventory = SupplyInventory.create! valid_attributes
      expect {
        delete supply_inventory_url(supply_inventory)
      }.to change(SupplyInventory, :count).by(-1)
    end

    it "redirects to the supply_inventories list" do
      supply_inventory = SupplyInventory.create! valid_attributes
      delete supply_inventory_url(supply_inventory)
      expect(response).to redirect_to(supply_inventories_url)
    end
  end
end
